In [109]:
import numpy as np

#### 1

In [111]:
nums_16 = np.arange(1,17)
print(nums_16)
re_num16 = nums_16.reshape(4,4)
print(re_num16)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### 2

In [113]:
nums_50 = np.arange(10,50,5)
print(nums_50)
nums_2_4 = nums_50.reshape(2,4)
print(nums_2_4)

[10 15 20 25 30 35 40 45]
[[10 15 20 25]
 [30 35 40 45]]


#### 3

In [115]:
nums100 = np.random.randint(1,100,size=(3,3))
print(nums100)
print(f"min- {nums100.argmin()} max - {nums100.argmax()}") # the indexs
print(f"min- {nums100.min()} max - {nums100.max()}") # the values (answer)

[[49  5 13]
 [40 73 74]
 [24 23  7]]
min- 1 max - 5
min- 5 max - 74


In [116]:
#### 4

In [117]:
num0_20 = np.arange(0,21)
print(num0_20)
print(f" 1)- {num0_20[0:5]}")
print(f" 2)- {num0_20[0:21:2]}")
print(f" 3)- {num0_20[::-1]}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 1)- [0 1 2 3 4]
 2)- [ 0  2  4  6  8 10 12 14 16 18 20]
 3)- [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 5

In [119]:
nums1_50 = np.random.randint(1,51,size=(4,5))
print(nums1_50)
print(f"second line -{nums1_50[1]}")
for lst in nums1_50:
    print(f"column 4 - {lst[3]}")

[[35 30  9 33 16]
 [43  9  9 21 46]
 [36 31  9 31  8]
 [29 13 18 50 20]]
second line -[43  9  9 21 46]
column 4 - 33
column 4 - 21
column 4 - 31
column 4 - 50


#### 6

In [121]:
rand100 = np.random.randint(1,101,size=(1,15))
print(rand100)
print(f"min- {rand100.argmin()} max - {rand100.argmax()}") # the indexs

[[ 4 64 68 57 83 92 20 33 84 84 32 74 60 36 82]]
min- 0 max - 5


In [122]:
np.save("answer6-randint100",rand100)

In [123]:
load_arr = np.load("answer6-randint100.npy")
print(load_arr)
print(load_arr[(load_arr%5==0)])
print(load_arr[(load_arr > 50) | (load_arr <10)])

[[ 4 64 68 57 83 92 20 33 84 84 32 74 60 36 82]]
[20 60]
[ 4 64 68 57 83 92 84 84 74 60 82]
